### ISSUE TITLE
How to evaluate alignment quality?

### ISSUE THREAD

**Issue by platers** [meinardmueller/synctoolbox#21]
Thanks for making this library! I'm a noob to this field, so I may be missing something obvious.

Is there a metric returned somewhere that indicates how well two audio tracks align? My use case is determining if a song is a cover of another, e.g. a pop song to a piano or guitar cover.

**Comment by ahnonay** [comment]
Dear Victor,

thanks for your interest in synctoolbox.

You could compare the quality of alignments by looking at the total alignment costs. However, be careful to normalize these costs by the lengths of the warping paths (otherwise, longer songs will always have worse costs).

In general, you will get problems using this alignment approach if the original song and the cover song have structural differences. Thus, you may want to search for some more suitable approaches for your task. Keywords include 'cover song identification' and 'version identification'. 

Best,
Michael

Am 25. November 2022 07:02:30 MEZ schrieb Victor Tao ***@***.***>:

**Comment by platers** [comment]
Thanks!
